//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int product_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double unit_price { get; set; }
        public int qty { get; set; }
    }
}
